name: jenkins-operator
operator:
  image:
    name: epamedp/jenkins-operator
    version: 2.13.2
  serviceAccountName: jenkins-operator
  clusterRoleName: jenkins-operator-clusterrole

jenkins:
  logLevel: WARNING
  clusterRoleName: jenkins-clusterrole
  serviceAccountName: jenkins
  initImage:
    name: busybox
  image:
    name: epamedp/edp-jenkins
    version: 2.7.0
  storage:
    size: 10Gi
  sharedLibraries:
    edp-library-stages:
      url: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd.svc:32114/mdtu-ddm/devops/registry-regulations-publications/registry-regulations-publication-stages.git
      tag: build/1.5.0-SNAPSHOT.6
      secret: edp-gerrit-ciuser-sshkey
      type: ssh
    edp-library-pipelines:
      url: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd.svc:32114/mdtu-ddm/devops/registry-regulations-publications/registry-regulations-publication-pipeline.git
      tag: build/1.5.0-SNAPSHOT.239
      secret: edp-gerrit-ciuser-sshkey
      type: ssh
  jobProvisioner: registry
  port: "8080"
  jnlpPort: "50000"
  basePath: cicd

gerrit:
  basePath: gerrit

keycloakIntegration:
  enabled: true
  realm: administrator

monitoring:
  namespace: openshift-monitoring
  roleName: jenkins-monitoring-role

keycloak:
  host: platform-keycloak:8080
  clientName: jenkins-deployer
  secretName: jenkins-keycloak-client
  realm: admin

sentinel: {}

registryRegulation:
  cleanupVersionCandidateDBsCronSchedule: "TZ=Europe/Kiev\\n00 17 * * 1-5"

# Test values (actually are passed via deploy pipeline)
dockerRegistry: docker-registry.openshift-image-registry.svc
dockerProxyRegistry: docker-registry.openshift-image-registry.svc
global:
  storageClass: ocs-storagecluster-ceph-rbd
  platform: openshift
image:
  version: 1.1.1-1

edpComponent:
  description: "Програмний комплекс, що забезпечує автоматизацію в життєвому циклі розгортання регламенту Реєстру"
  displayName: "Сервіс розгортання регламенту (Jenkins)"
  operationalZone: "registry-administration-zone"

dnsWildcard: mdtu-ddm.edp.epam.com
edpProject: mdtu-ddm-edp-cicd
namespace: ns
cdPipelineName: pipe
cdPipelineStageName: dev
